version: "3"
services:
  leaves:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD: 'local'
    image: leaves:1.1
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://devuser:devpass@183.83.1.3/leaves
    networks:
      testing_net:
        ipv4_address: 183.83.1.2
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leaves
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 9906:3306
    networks:
      testing_net:
        ipv4_address: 183.83.1.3
volumes:
  db_data: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 183.83.0.0/16
